### ISSUE TITLE
Defining the conflux zip interface

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/conflux#2]
### Return value
To start with the obvious part, we'd want the return value of conflux's zip function to be easily piped to [`streamSaver.createWriteStream()`](https://github.com/jimmywarting/StreamSaver.js), meaning we'll want to return a single `ReadableStream`. 

```js
confluxReturnValue.pipeTo(streamSaver.createWriteStream('download.zip'));
```

#### As a WritableStream
From @jimmywarting:
```js
// Write entries manually
const writer = conflux.writable.getWriter();
writer.write(new File(['demo'], 'sample.txt'));
writer.close();
```

#### As a function
Presumably we'd want a list of ReadableStreams as input, with some metadata about the files and where they sit in the underlying folder structure.
- `ReadableStream`
- `fileName`
- `filePath`
- more?

```js
const zip = new ZIP();

zip.addSources([{
  readable: rs,
  fileName: 'cat.jpg',
  filePath: 'animals'
}, {...}])

zip.generate()
  .pipeTo(streamSaver.createWriteStream('download.zip'));
```

## The File API
I don't think we'd want to force users to use the [File API](https://developer.mozilla.org/en-US/docs/Web/API/File). As far as I can tell, it uses blobs only, which would create a bottleneck in the stream pipeline that we're seeking to enable here.

**Comment by jimmywarting** [comment]
> **The File API**
> I don't think we'd want to force users to use the File API. As far as I can tell, it uses blobs only, which would create a bottleneck in the stream pipeline that we're seeking to enable here.

My current zip streamer as it's now don't really use Blobs or Files. it just use some of the same IDL properties/methods as the File API has. The reason I choose to use that is cuz it would have made it easy to add a `File` object without having to map a file to an object so you could do either

```js
file = new File(['mjau'], 'folder/cat.jpg', { lastModified: new Date(0) })
writer.write(file)
// or
writer.write({
  name: 'folder/cat.jpg', // required, same as file.name
  stream: () => readable, // required, same as file.stream()
  lastModified: new Date(0) // optional, same as file.lastModified
})
```
and you would be familiar with something similar like File that have existed for a long time

The reason for using a funktion `stream() { ... }` and not `{ stream: readable }` was
1. I didn't want to have a different structure then the File IDL, so it works with both custom object and Files.
2. I didn't want to initiate multiple read descriptor to versis places (disc, fetch, etc) before the zip streamer needed it or something else down the line (pipedTo) started to consume something. 
3. it would also make it easier to abort/close the zip so you don't have to close each and every stream you have initiated with something like
```js
zip.addSources([{
  readable: rs
  ...
},{
  readable: rs
  ...
}])
```
4. What if you needed to read the file over again for some reason?
5. you could always create a own data class wrapper around other object as long as it normalizes all classes to have `stream()` and `name` 

```js
class SomeClass extends String {
  get name () { ... }
  stream () {
    // convert data to a readable stream over and over again when needed (makes it reusable)
    var { readable, writable } = new TextEncoderStream()
    var writer = writable.getWriter()
    writer.write(this)
    writer.close()
    return readable

    // you could also create a readableStream and just
    // write a Uint8array instead of using TextEncoderStream...
  }
}

data = new SomeClass('data')
zipWriter.write(data)
```

**annevk** [mention](https://bit.ly/2RUjuqj) using [symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) for normalising anything (like FormData) to a stream and I thought that sounded amazing but they settled with `stream()`... so thats why i also choose `stream()` as well.

> **Name+Path**

```js
  fileName: 'cat.jpg',
  filePath: 'animals'
```
vs just
```js
  name: '/animals/cat.jpg'
```
vs just
```js
  fullPath: '/animals/cat.jpg'
```
just for simplicity... i guess name or fullPath is easier? Writing a zip entry use full path... can be used for both files and folder. having just one property makes it easier. just add `{ folder: true }` to indicate that it's a folder and not a file, but you normally never have to create folders, zip application will recursively create directories if they don't exist before unpacking even if a folder entry don't exist in the zip archive?.
for background, `input[type=file][webkitdirectory] yields `webkitRelativePath`, FileEntries from drag and drop have [fullPath](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry)

> **As function/WritableStream**

I prefer Write entries manually with writableStream instead of `addSources`

- The less custom method you have the easier it could be for others to understand how to use it since they already know how streams work. the most similar thing being text encoder stream
- you can pipe and transform
- you can use [queueing strategies](https://streams.spec.whatwg.org/#queuing-strategies)
- reading folders like `find('**/*.log').pipeThrough(zip).pipeTo(streamSaver)` will make `find(...)` only scan folders when needed, if user pause or abort the download then `find(...)` don't have to scan the hole directory in vain
- `addSources` + `generate()` requires you to know everything beforehand. it makes it less streamable (you can't start right away)

**Comment by jimmywarting** [comment]
puh, that got a bit long, sorry for that.

**Comment by jimmywarting** [comment]
This made it easer since the transform function will only handle one entry at the time as where the old zip streamer had to handle a queue, you can ofc still enqueue/push more items but the transform function don't need to care about that

**Comment by jimmywarting** [comment]
Maybe we should have something like:

```js
class Something extends TransformStream { ... }
```

**Comment by bencmbrook** [comment]
@jimmywarting yup, all very solid reasoning. I'm convinced the WritableStream API is best and that matching the File IDL makes sense. The TransformStream at the core is really nice. Are we concerned at all about browser compatibility with Transform / Writable streams?

Any performance concerns from going sequential? If I'm fetching from two remote sources and the first one starts lagging, is the zip streamer bottlenecked?

Also, we're game to use a compiler. Good for Babel, TypeScript, ES8 etc.

**Comment by jimmywarting** [comment]
I would be down for not using any compiler also. But it also depends on target support.

I'm not a big fan of using TypeScript...

Yes, zip streamer would be a bottleneck. But so was the "old" original zip streamer I wrote also. Not sure if it would be any befit to use concurrency, you have to write the zip entries in order

**Comment by jimmywarting** [comment]
You could always fetch 2 resources and get the response.body 
Then you would already have started the download. 

What would you say if set the lowest targeted support to be browser that has support for import?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Helping the hole community to push for a more "evergreen" browser.
This is the time to do so when http2 have gotten a wider support
Good for lazy loading also

**Comment by jimmywarting** [comment]
Don't like that websites bundle the hole application into one large file and you only use a fraction of it

**Comment by bencmbrook** [comment]
> Not sure if it would be any befit to use concurrency, you have to write the zip entries in order

Having async would be pretty awesome in the case when a source stream stops flowing. It seems like it's been done but this isn't the highest priority. Relevant [blog post](http://www.pixeldonor.com/2013/oct/12/concurrent-zip-compression-java-nio/) and [source code](https://github.com/iamjem/java-simplezip/blob/master/src/main/java/com/pixeldonor/ThreadedArchiver.java).

**Comment by jimmywarting** [comment]
> > Not sure if it would be any befit to use concurrency, you have to write the zip entries in order
> 
> Having async would be pretty awesome in the case where a source stream stops flowing. It seems like it's been done but this isn't the highest priority. Relevant [blog post](http://www.pixeldonor.com/2013/oct/12/concurrent-zip-compression-java-nio/) and [source code](https://github.com/iamjem/java-simplezip/blob/master/src/main/java/com/pixeldonor/ThreadedArchiver.java).

i thought about it also, it's possible to work on each entry individually at the same time and then pipe all compressed data into a final zip builder

But at what cost? what if you compress two large files (2x2GB)
you would not be able to flush the second content if you already piping the first file (the stream would be locked to one reader and then released when the first one finish). it would be either that or some race condition until a entry is completely compressed, and only then would it start to write the data to the zip archive but then you would have to have both in the memory at the same time.

it could work okey for many smaller files but how about when they are much larger? you don't know if you are dealing with a low quality mobile device when you make anything public on the web
it would also be best if you could then use [navigator.hardwareConcurrency](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency) and the chrome only [Performance.memory](https://developer.mozilla.org/en-US/docs/Web/API/Performance) api's

would make this a bit more complex..

**Comment by jimmywarting** [comment]
> Are we concerned at all about browser compatibility with Transform / Writable streams?

For none other then Blink you would need the web stream ponyfill for the time being...
recommend that we also do what i did with StreamSaver
```js
StreamSaver.TransformStream = window.TransformStream || ponyfill.TransformStream
```
since the web stream polyfill don't use the native ReadableStream and that creates some complications

**Comment by bencmbrook** [comment]
> it could work okey for many smaller files but how about when they are much larger?

Sounds like a fun optimization problem for the future :) if we have knowledge of content length we could do it

**Comment by bencmbrook** [comment]
Regarding target support, import feels aggressive (FF only supported it last month). For this to be widely useful we should have better support. 

Maybe we match StreamSaver.js since it’s a likely pairing? 

I can set up Babel and Webpack if we want it.

**Comment by jimmywarting** [comment]
> Sounds like a fun optimization problem for the future :) if we have knowledge of content length we could do it

knowing the size beforehand was one of the requirement in zip.js, partly why i rolled my own so i didn't have to. 

Maybe create a new issue and add it to the backlog. 
Lets first see how this compares to other libs when we have written some benchmark

**Comment by eligrey** [comment]
I concur with @bencmbrook regarding everything @jimmywarting has suggested for the API.

**Comment by eligrey** [comment]
I concur with @bencmbrook regarding everything @jimmywarting has suggested for the API.

I also think we should probably hold off on multi-thread optimizations until this project is in a more flushed-out state.

**Comment by jimmywarting** [comment]
here is a basic idea of how concurrency could work
```js
// Entry transformer
function ZipEntryTransformer () {
  return new TransformStream({
    start () {
      // write entry heder metadata
    }
    transform (chunk, ctrl) {
      chunk = new TextDecoder().decode(chunk)
      ctrl.enqueue(chunk.toUpperCase())
    },
    flush () {
      // write entry footer data
    }
    writableStrategy: { ... },
    readableStrategy: { ... }
  })
}

let a1 = new Response('usa').body.pipeThrough( new ZipEntryTransformer() )
let a2 = new Response('sweden').body.pipeThrough( new ZipEntryTransformer() )

let fileStream = new WritableStream({ write: c => console.log(c) })

await a1.pipeTo(fileStream, { preventClose: true })
await a2.pipeTo(fileStream)
```

**Comment by jimmywarting** [comment]
I was thinking more about the above method before in the weekend.

There is one problem about the current method that is: If you cancel a zip generation it would still continue reading the file but not add any new entries. that's because you only abort adding new zip entries 

this piece of code will still run.

https://github.com/transcend-io/conflux/blob/97d55ad1c069e4c89f62d902d1b298301236ec1a/write.js#L62-L71

it would be better if it was piped to one and only zip stream like the previous (above) comment.
dose removing the need for a `read while true` 
- it would respect the queueing strategy you provide
- it would abort/pause the current file reading if the zip generation is paused as well
  - it would also respect the watermark limit and not overflow the queue (if you are generating faster then what you are able to save)
