### ISSUE TITLE
Performances testing

### ISSUE THREAD

**Issue by jimmywarting** [transcend-io/conflux#4]
Compare the speed agains browser based zip packages

- [ ] [JSZip](https://github.com/Stuk/jszip), 
- [ ] [zip.js](https://gildas-lormeau.github.io/zip.js/)
- [ ] conflux
- something else?

**Comment by bencmbrook** [comment]
Could create a running benchmark on our CI with something like this [Benchmark.js](https://github.com/bestiejs/benchmark.js/)

I'd recommend we benchmark a simple pipeline like this to start:
- Fetch 5 files (files should be local to remove noise due to network speeds)
- zip them
- Save to disk

Since conflux is a transform stream, we would want to measure the time to complete the pipeline. I imagine we'd also want to measure the max memory.

**Comment by jimmywarting** [comment]
Max memory +1

Not sure about fetching remote files and save it to the disc. Think that would make it unreliable. Think we should pre create files in the browser and measure how long time it takes to get a blob or pipe it to a noop stream

Besides hard to automate save to disc

**Comment by bencmbrook** [comment]
Yeah that works better. 

We would want to start with the source data being a ReadableStream though, so we can measure the cost of buffering the data into a blob before calling JSZip/zip.js.

**Comment by jimmywarting** [comment]
I think it could be fair to start out with a File object for all three

jszip/zip.js would both start out reading the file using fileReader
and conflux would just call the newly added `file.stream()` method

**Comment by jimmywarting** [comment]
oh, btw

When we are testing other libs we wanted to see how much memory they consume.
to figure that out we need to use `performance.memory` (and it's only available in Blink)
it's not possible to garbage collect so maybe we can run it in a worker thread? or just measure how much ram is used and diff before and after

**Comment by jimmywarting** [comment]
I'm also curious to compare babelified and none babelified version - to see how much overhead babel adds
