### ISSUE TITLE
conflux ignores backpressure

### ISSUE THREAD

**Issue by rowanG077** [transcend-io/conflux#92]
First of aIl thank you for this nice library!

I have a streaming stack which works fine but one of the things that conflux does not handle is back pressure. This is relatively important for my use case since I'm zipping large files that then get uploaded. Of course zipping is much faster then uploading so it essentially just keeps the entire zip file in memory which means streaming doesn't do much.

**Comment by bencmbrook** [comment]
Hey @rowanG077 thank you for saying so, and thanks for this report.

Can you clarify how you're interfacing with conflux? Are you using `writer.write()` as shown [here](https://github.com/transcend-io/conflux#writing-a-zip) or `myReadable.pipeThrough(new Writer())` as shown [here](https://codesandbox.io/s/transcend-ioconflux-writing-x8vq4?file=/src/index.js)?

**Comment by eligrey** [comment]
@rowanG077 Thank you for the feedback! It's on our roadmap to eventually add support for backpressure propagation and adopt the use of `queuingStrategy: { highWaterMark }`.

This is not currently prioritized. If you want to contribute a fix in the meantime, we are very receptive of PRs!

**Comment by eligrey** [comment]
@rowanG077 Would it be as simple as providing a parameter in our API so that you can pass in your own queuing strategy object?

**Comment by rowanG077** [comment]
@bencmbrook I'm using `myReadable.pipeThrough(new Writer())`!

@eligrey  This is possible. But this bug report is more about Conflux respecting the stream it writes to. So if it detects the stream it writes to applies backpressure it should stop. This is seperate from Conflux itself applying backpressure.

**Comment by bencmbrook** [comment]
Thanks for the clarification @rowanG077 😊. To be clear, have you discovered that Conflux is failing to pass the backpressure signal back upstream to the original source? Or are you saying that Conflux is not regulating the rate of events it enqueues on the writable side?

If the latter: _(TLDR: it's the responsibility of the original source to respect the backpressure, and thereby manage memory overhead.)_ Other than passing the backpressure signal backward toward the original source, TransformStreams can't do much to regulate a pipe chain's rate of flow. Backpressure is signaled from the ultimate sink (the last writable / end of the pipe chain), "back" to the original source (the first readable / beginning of the pipe chain). The transformers in between merely pass the backpressure signal backward toward the original source.

Other than passing the signal along, TransformStreams aren't able to reduce the rate of flow. For example, if we updated Conflux to recognize a backpressure signal and act on it by reducing the rate at which we enqueue events onto the readable side, the queue of chunks would merely grow inside Conflux, since the writable is still receiving data from the source. So instead, the TransformStream just passes the message along to the original source, where the flow can truly be adjusted.

**Comment by bencmbrook** [comment]
Closing this out for now but let us know if anything is awry regarding the backpressure signal :)
